Use column layout for hotkeys
cloudflare/workers-sdk pull request #2503
Opened 2023-01-05 15:23 UTC by penalosa

What this PR solves / how to test:

On small terminal windows, Ink was hiding the keys needed to use the hotkeys interface. This PR switched to a column layout so the keys are visible on more terminal sizes.

Before:
<img width="492" alt="Screenshot 2023-01-05 at 15 15 48" src="https://user-images.githubusercontent.com/28503158/210815491-5791caf7-3b84-495d-a956-277001b69b98.png">

After:
<img width="524" alt="Screenshot 2023-01-05 at 15 22 22" src="https://user-images.githubusercontent.com/28503158/210815548-445a7c5e-6479-408c-8d1f-961407626461.png">

2023-01-05 15:40 UTC, JacobMGEvans commented
Im guessing due to the nature of how a terminal outputs its UI, we can't make it responsive?

2023-01-05 17:01 UTC, penalosa commented
> Im guessing due to the nature of how a terminal outputs its UI, we can't make it responsive?

I don't think we can, I'm afraid (perhaps someone more familiar with Ink than me would know if this is possible). Having said that, I think this is slightly nicer _anyway_, for being able to see all options at a glance.

2023-01-05 17:38 UTC, JacobMGEvans commented
> > Im guessing due to the nature of how a terminal outputs its UI, we can't make it responsive?
> 
> I don't think we can, I'm afraid (perhaps someone more familiar with Ink than me would know if this is possible). Having said that, I think this is slightly nicer _anyway_, for being able to see all options at a glance.

And we are trying to remove Ink 😅

2023-01-05 17:38 UTC, JacobMGEvans approved these changes

2023-01-05 19:21 UTC, JacobMGEvans commented
> I'm slightly concerned about this change wrt integrated terminals, it uses lots of the limited vertical space. If we could get this to be responsive, that would be great. Could you use `process.stdout.columns`, and the [`resize` event](https://nodejs.org/api/tty.html#event-resize)? Maybe change the text too to make it shorter, i.e. `open a browser` -> `browser`, `to exit` -> `exit`, .... ![image](https://user-images.githubusercontent.com/15955327/210846848-982fcc9d-c46b-4fae-92db-1c35c99f3769.png)

That would be awesome, I know we had tried using the columns/resize before but to get it to "rerender" either had to clear it or keep the old jank ones in the scroll history.

2023-01-11 18:26 UTC, JacobMGEvans requested changes
Based on the quoted comment and this comment we should look more into this
https://github.com/cloudflare/wrangler2/pull/2503#issuecomment-1372633530

2023-01-12 23:11 UTC, JacobMGEvans commented
@mrbbot This is the old issue that I think referred to the resize event https://github.com/cloudflare/wrangler2/issues/374

2023-02-17 15:26 UTC, penalosa commented
Closing this for now. We can re-evaluate when Ink is removed, and do something based on `process.stdout.columns`

2023-02-17 15:26 UTC, closed without merging