Add --node-compat to Pages publish
cloudflare/workers-sdk pull request #2541
Opened 2023-01-12 23:59 UTC by WalshyDev

What this PR solves / how to test:

This adds `--node-compat` support to Pages, this is a common feature request and will allow for the usage of Stripe and other such libs within Functions.

Associated docs issues/PR:
N/A

Author has included the following, where applicable:

- [ ] Tests
- [x] Changeset

Reviewer has performed the following, where applicable:

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes #1074

2023-01-13 00:00 UTC, GregBrimble commented
https://github.com/cloudflare/wrangler2/pull/2540#issuecomment-1381121155

2023-01-13 00:05 UTC, WalshyDev commented
> I'd like to hold on this until we see where this new nodejs_compat compatibility flag goes, especially since we don't have an in-dash option for this at the moment. I think we're going to quite quickly be at a point where using this polyfill is more harmful than good.

The nodejs compat flag won't have parity for quite a while. In-dash option is also not a blocker, we've done this many times and it takes no time at all to this to the UI. 
Considering we already support this in dev and build, I see no reason to not just add it here. People have wanted it ever since Functions was made. This brings us closer in parity with Workers and for basically 0 cost.

This also means the migration to the new flag is also the same rather than being _another_ thing different.

2023-01-13 15:24 UTC, JacobMGEvans requested changes
Looks great, would like to see an integration test for this before it goes in, probably should go here: https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/__tests__/pages.test.ts 😃

2023-01-13 15:24 UTC, JacobMGEvans commented on packages/wrangler/src/pages/publish.tsx
> +		}
Could you add a test that runs `wrangler pages publish --node-compat`

2023-01-13 16:41 UTC, JacobMGEvans commented
> > I'd like to hold on this until we see where this new nodejs_compat compatibility flag goes, especially since we don't have an in-dash option for this at the moment. I think we're going to quite quickly be at a point where using this polyfill is more harmful than good.
> 
> The nodejs compat flag won't have parity for quite a while. In-dash option is also not a blocker, we've done this many times and it takes no time at all to this to the UI. Considering we already support this in dev and build, I see no reason to not just add it here. People have wanted it ever since Functions was made. This brings us closer in parity with Workers and for basically 0 cost.
> 
> This also means the migration to the new flag is also the same rather than being _another_ thing different.

I agree with this take on the polyfill `--node-compat` the runtime compat flag won't directly interfere with this implementation, they just cannot be used together.

2023-02-20 20:26 UTC, notwedtm commented
Any updates on when this might get merged in?

2023-09-29 13:28 UTC, jadbox commented
I'm needing to bump this as it's September now without updates. This feature is critical for using PG via tcp balancing on Cloudflare Pages functions.

2023-09-29 13:48 UTC, jadbox commented
I'm blocked from going into production with CF pages due to this bug. This prevents me from using PG tcp pooling in my Page workers.

The other issue is that I'm unable to test against remote data with Pages workers due to this bug:
https://github.com/cloudflare/workers-sdk/pull/2541

2023-10-02 16:08 UTC, GregBrimble submitted a review, later dismissed
Blocking until we've had internal product roadmap discussions.

2023-10-31 20:04 UTC, GregBrimble commented
Rather than accepting this as a arg on deploy, should we instead look at the config of the project in the dashboard and use that so it's all kept in one place? Sort of like how we did D1 when it was in beta and needed the shims?

2023-10-31 20:41 UTC, WalshyDev commented
It's already an arg for Workers, if we did move it we'd also need to change dev behaviour to pull from the project which just diverges us more from Workers.

2023-10-31 21:19 UTC, GregBrimble commented
But we don't yet have it for many other similar props like compat date and flags. Feels like we should solve syncing config separately to adding this node compat feature (so should stay consistent until we've got that bit figured out in a separate effort).

2023-12-09 14:57 UTC, janpio commented
I can confirm that using the [prerelease version mentioned above](https://github.com/cloudflare/workers-sdk/pull/2541#issuecomment-1381123337) indeed let's me _deploy_ a project using `pg` to GitHub Pages that I could not deploy before, as the build was running into [weird errors messages](https://discord.com/channels/595317990191398933/1183055574225670314) (which means that `nodejs_compat` just does not work here). Unfortunately the deployment does not seem to work though, requests get a 522 and the deployment shows "Failed" in the web UI.

@WalshyDev Is this supposed to work on the deployed side as well or is this PR here only one side of the coin and there would need to be a change on the platform as well?

We would really appreciate if this could be added to the stable version of `wrangler`, even if undocumented similar to `--node-compat` for `dev`. Then it could still be removed or updated later when you figure out the long term strategy around node compatiblity.

2023-12-24 11:04 UTC, Hebilicious commented
Hi @janpio!
If I understand correctly, you were you able to deploy a project to cloudflare pages with `pg` has a dependency, and then you can use postgres from cloudflare pages without issues?

2024-01-02 11:42 UTC, petebacondarwin approved these changes
This feels like a reasonable addition, given that it is already supported by Pages `dev` and `build` commands.

What's left to get this ready to be merged?

2024-01-10 00:29 UTC, janpio commented
@Hebilicious Yes, this change to the CLI unblock usage of `pg` in Cloudflare Pages functions mostly. (It does not work when you also want to use Next.js, but that is a separate problem: https://github.com/cloudflare/next-on-pages/issues/605)

2024-01-10 14:56 UTC, petebacondarwin commented
I think a workaround for now is to use `wrangler pages build functions --node-compat build-output-directory=public/_worker.js` to generate the Pages Worker and then upload that using `wrangler publish public`.

Does that work for your use case?

2024-01-22 16:24 UTC, admah commented
@WalshyDev it looks like this failed on a formatting issue. Could you fix that and we should be good to merge?

2024-01-22 18:20 UTC, GregBrimble requested changes
I think we still first need to discuss and make a clear decision on how this impacts the source of truth for this currently dash-only config setting. This, although aligns with Workers in some ways by exposing this CLI arg in the `deploy` command, misaligns with Pages in others, in that this setting can now be configured completely independently of our source-of-truth: the dashboard.

2024-02-01 16:30 UTC, janpio commented
@GregBrimble Can `node_compat` (or `--node-compat`) actually be configured via the UI/dashboard? 

In my (external) understanding `node_compat` is a _build-time_ flag that influences how the CLI builds the code of your worker (by adding a bunch of polyfills that makes for example `pg` work), and `nodejs_compat` is a _runtime_ compatibility flag that influences how the code that has been uploaded is being run on the worker, or what code is available when it runs (like some node APIs in the case of `nodejs_compat`).

2024-02-19 13:30 UTC, petebacondarwin commented
Since this PR is very unlikely to land as-is (e.g. we actually want to make nodejs compat flag the approach to take in the long run) and this PR has been sitting around for quite some time, we are going to close it for now. If and when we decide to implement the `node-compat` build time setting for Pages we can reopen or reimplement this.

2024-02-19 13:30 UTC, closed without merging

2024-02-19 14:11 UTC, janpio commented
What is the recommended workaround in the meantime @petebacondarwin? Right now it seems that `pg` is not usable with Cloudflare Pages then (as it requires `node-compat`).

2024-02-19 14:24 UTC, petebacondarwin commented
@janpio - can you try the workaround here?

https://github.com/cloudflare/workers-sdk/pull/2541#issuecomment-1885006209

2024-02-19 14:41 UTC, janpio commented
Oh sorry, we tried that but seem to have forgotten to report back:

1. The command there is invalid, I assume the correct order would be `wrangler pages functions build --node-compat build-output-directory=public/_worker.js`
2. Then it fails during the `publish`:
	```
	▲ [WARNING] `wrangler publish` is deprecated and will be removed in the next major version.
	
	  Please use `wrangler deploy` instead, which accepts exactly the same arguments.
	
	
	
	✘ [ERROR] A compatibility_date is required when publishing. Add the following to your wrangler.toml file:.
	
	      ```
	      compatibility_date = "2024-02-01"
	      ```
	      Or you could pass it in your terminal as `--compatibility-date 2024-02-01`
	  See https://developers.cloudflare.com/workers/platform/compatibility-dates for more information.
	```

Full setup here: https://github.com/prisma/ecosystem-tests/pull/4504 + https://github.com/prisma/ecosystem-tests/actions/runs/7743032416/job/21113520833?pr=4504#step:8:147

2024-02-19 14:47 UTC, petebacondarwin commented
OK let me reproduce. The error message seems to imply you are only missing `--compatibility-date` flag?

2024-02-19 15:45 UTC, janpio commented
Indeed. Although I now realized that `wrangler publish` publishes a Worker and not Pages. What is required to build the whole Pages "combination" and deploy it?

2024-02-19 16:16 UTC, petebacondarwin commented
Yeah sorry about this. It is all a bit messy right now. Trying to work out if there is a magical combination of commands that we could use.

2024-02-19 16:35 UTC, petebacondarwin commented
Give this a go: https://github.com/prisma/ecosystem-tests/pull/4574

2024-02-19 21:19 UTC, millsp commented
Coming here to report that Pete's workaround is [working](https://github.com/prisma/ecosystem-tests/blob/dev/driver-adapters-wasm/pg-cfpages-basic/run.sh#L15-L19) well :rocket:. Thanks!

2024-02-20 13:23 UTC, Hebilicious commented
@petebacondarwin Is there any chance that the workaround could be documented in the Pages docs, or at least here ?
I believe using `pg` in cloudflare pages is quite common.

2024-02-26 16:48 UTC, delay commented
Maybe you should consider updating your documentation because as far as I can tell this still isn't working with pg.  The workaround I have found is to use the postgres npm package instead.  https://developers.cloudflare.com/workers/tutorials/postgres/

2024-05-02 10:46 UTC, petebacondarwin commented
> Maybe you should consider updating your [documentation ](https://developers.cloudflare.com/workers/tutorials/postgres/) because as far as I can tell this still isn't working with pg and Pages. The workaround I have found is to use the postgres npm package instead of pg.

We should update that to make it clear that the tutorial is for Workers not Pages.