templates(worker-rust): bump versions and fix lints
cloudflare/workers-sdk pull request #2812
Opened 2023-02-27 18:39 UTC by KianNH

What this PR solves / how to test: Current `worker-rust` template doesn't work due to outdated crate versions (`worker-build`).

Also bumps other dependencies & fixes lints.

Associated docs issues/PR:

- https://github.com/cloudflare/workers-rs/issues/282
- https://github.com/cloudflare/workers-sdk/issues/2751

2023-02-27 18:40 UTC, KianNH commented
cc @zebp

2023-03-03 16:00 UTC, JacobMGEvans approved these changes
Template seems to be working for me. Thanks for the fix and improvements!

2023-03-03 16:14 UTC, KianNH commented
Rebased

2023-03-13 20:39 UTC, zebp requested changes
Sadly needs another bump

2023-03-13 20:39 UTC, zebp commented on templates/worker-rust/Cargo.toml
> +worker = "0.0.13"
We just released `0.0.14` so this needs to be updated again

2023-03-20 19:45 UTC, closed without merging