Add advanced code example to documentation
cloudflare/workers-sdk pull request #3026
Opened 2023-04-11 23:06 UTC by Alex1607

**What this PR solves / how to test:**
In my opinion removing the code example and just using a barebone file leaves a lot of newstartes in the dark. Therefor I added the old code as an advanced example to the documentation.

**Associated docs issue(s)/PR(s):**
- #2936

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer has performed the following, where applicable:**

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

2023-04-11 23:25 UTC, JacobMGEvans commented
Please run Prettier 
`npm run fix`

2023-04-11 23:34 UTC, JacobMGEvans requested changes
The messaging needs some rewording and the formatter needs to be ran on the file. If the formatter makes the snippet look off we can add that to the prettier/linter ignore

2023-04-11 23:34 UTC, JacobMGEvans commented on templates/experimental/worker-rust/README.md
> +Given that this template only contains the most basic setup, you might want to use this more advanced example. It demonstrates how you can create multiple routes, log requests, get field data from a
```suggestion
As this template comprises only the essential setup, we recommend considering our advanced example to leverage its additional functionalities. The advanced example showcases the creation of multiple routes, logging of requests, retrieval of field data from a form, and other features that may prove useful to your project.
```

2023-04-12 16:46 UTC, Alex1607 commented
Checks are failing because a test timed out: `→ Test timed out in 30000ms.`
I don't think it's related to my changes.

2023-05-03 14:16 UTC, nouzu commented
I suggest we use example from the workers-rs repo, it's compact and does the job.

```rust
use worker::*;

#[event(fetch)]
pub async fn main(req: Request, env: Env, _ctx: worker::Context) -> Result<Response> {
    console_log!(
        "{} {}, located at: {:?}, within: {}",
        req.method().to_string(),
        req.path(),
        req.cf().coordinates().unwrap_or_default(),
        req.cf().region().unwrap_or("unknown region".into())
    );

    if !matches!(req.method(), Method::Post) {
        return Response::error("Method Not Allowed", 405);
    }

    if let Some(file) = req.form_data().await?.get("file") {
        return match file {
            FormEntry::File(buf) => {
                Response::ok(&format!("size = {}", buf.bytes().await?.len()))
            }
            _ => Response::error("`file` part of POST form must be a file", 400),
        };
    }

    Response::error("Bad Request", 400)
}
```

2023-08-21 15:37 UTC, JacobMGEvans approved these changes

2023-10-23 15:29 UTC, jspspike commented
@Alex1607 Could this link to `workers-rs` README? Since this is just a copy of that I feel like that would make sense in the case the reader wants to read more or any changes are made to this example based on changes in `workers-rs`. Honestly I feel like it would make the most sense to remove the snippet entirely and just say you could go to this link for more info but if you feel like it makes sense to include it that's fine with me

2023-11-15 19:26 UTC, Alex1607 commented
@jspspike @lrapoport-cf sorry for the delay, I just adjusted the readme

2023-11-15 19:32 UTC, jspspike approved these changes
Looks good to me

2023-11-15 20:39 UTC, Alex1607 commented
How is the merging done? Do I still have to do something, or will someone take over from now?

2023-11-15 21:51 UTC, merged

2023-11-15 21:52 UTC, lrapoport-cf commented
thanks @Alex1607 , we've merged the change 👍