Adds constellation templates
cloudflare/workers-sdk pull request #3718
Opened 2023-08-08 14:25 UTC by celso

**What this PR solves / how to test:**

This PR adds constellation code templates.

**Associated docs issue(s)/PR(s):**

The code templates include README.md files.

2023-08-14 19:59 UTC, lrapoport-cf commented
hi @celso :) it looks like one of the checks is failing, would you be able to address this? i think you may need to run `npm run prettify`

2023-08-17 20:26 UTC, JacobMGEvans requested changes
I see there was an attempt to get Prettier to format and fix the issues, if it continues to be an issue feel free to reach out to me. 

I have a few comments, concerns and suggestions 😄 

Great PR, thanks for such an awesome contributions. 🎉

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/petal-length/data/Makefile
This could arguably be made to work with `package.json` with the Python script. I think this is less necessary to run traditionally in `package.json` and would take an additional script file running an exec command on that Python script anyway.

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/petal-length/data/convert2onnx.py
Aren't there [ONNX tooling for JS](https://onnxruntime.ai/docs/get-started/with-javascript.html)? That would allow for the file to be `.js` rather than Python remove a language dep and let the JS ecosystem tooling handle the script.

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/text-processing/src/index.ts
> +var SENTIMENT_ANALYSIS_PIPELINE: Pipeline;
Its generally best practice to use `let` for reassignable variables, it is block scoped and can help prevent odd bugs from `var`'s hoisting behavior. This in regards to all the use of `var` in the template, just picking a place to mention it.

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/text-processing/src/index.ts
> +async function classify_sentiment(
Consistent `camelCase` with function, variable, ect... naming in JS

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/text-processing/src/index.ts
> +import _ from "lodash";
Where is this being used? If I just missed it, is it something that can just be done with native JS API

https://youmightnotneed.com/lodash

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/text-processing/tsconfig.json
Rather than using the `tsc --init` default, to stay consistent, I suggest using the `tsconfig.json` from the `worker-typescript` template. https://github.com/cloudflare/workers-sdk/blob/main/templates/worker-typescript/tsconfig.json

2023-08-17 20:26 UTC, JacobMGEvans commented on templates/examples/constellation/text-processing/tsconfig.json
Soon, this will be automated with TurboRepo Gen, for bootstrapping tests, configs, packages, etc...

2023-08-25 23:09 UTC, rawsh commented
Hi @celso, I'm trying to run the text-processing example locally and I'm getting 500s back from all of the endpoints. I'm assuming there is a necessary step of uploading the models used to constellation. Can I ask how the models are named / what are the steps for that?

Hope you don't mind me asking on your PR

2024-05-02 09:05 UTC, closed without merging