wrangler R2: Add Sippy support
cloudflare/workers-sdk pull request #4130
Opened 2023-10-06 18:07 UTC by vkrasnov

This change adds support for managing [Sippy](https://developers.cloudflare.com/r2/data-migration/sippy/) on an R2 bucket.
The change was tested manually as automated test would require keeping valid S3 and R2 credentials.

Approval ticket: CR-747953
Docs PR: https://github.com/cloudflare/cloudflare-docs/pull/12295

2023-10-30 15:28 UTC, RamIdeas commented
@vkrasnov it looks like the tests are failing because you haven't updated the snapshots

Can you run the tests locally with jest's `--updateSnapshot` flag and commit the updated snapshots please?

2023-11-02 18:47 UTC, KianNH commented
Sippy currently works with buckets created with jurisdictional restrictions, i.e EU, as long as the `cf-r2-jurisdiction` request header is provided (like in the `r2 bucket create` requests).

Would it be possible to add it to these commands as well? A user recently asked about using Sippy w/ EU buckets in the community Discord.

2023-11-20 17:06 UTC, lrapoport-cf commented
discussed with @vkrasnov and he plans to followup 👍

2023-11-22 14:11 UTC, vkrasnov commented
Done

2023-11-27 17:23 UTC, lrapoport-cf commented
@vkrasnov could you please follow up on if this is approved before landing?

2023-11-28 18:32 UTC, lrapoport-cf commented
i've linked the approval ticket in the description -- will remove `blocked-CO` label once approved :) thanks @vkrasnov !

2023-12-13 02:18 UTC, lrapoport-cf commented
approval ticket CR-747953 approved 👍

2023-12-13 08:42 UTC, Skye-31 commented
Are you planning to support jurisdictions as mentioned in https://github.com/cloudflare/workers-sdk/pull/4130#issuecomment-1791344383?

2023-12-14 18:12 UTC, vkrasnov commented
Added (and tested)  jurisdiction support

2023-12-18 16:18 UTC, lrapoport-cf requested changes
the relevant CR has been approved. once a docs PR has been linked (cc @jonesphillip ) this can be landed.

2023-12-18 18:11 UTC, lrapoport-cf approved these changes

2023-12-18 18:12 UTC, merged