Bump `kv-asset-handler` to latest release
cloudflare/workers-sdk pull request #4237
Opened 2023-10-19 15:03 UTC by itsmatteomanf

**What this PR solves / how to test:**

Bumps `kv-asset-handler` to the latest v0.3.0 release, no breaking changes, just fixes.

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

2024-02-19 13:33 UTC, petebacondarwin commented
I believe we achieved this when we brought the kv-asset-handler over to the workers-sdk monorepo.

2024-02-19 15:21 UTC, itsmatteomanf commented
@petebacondarwin the files look unchanged to me in the current main branch...

2024-02-19 16:17 UTC, petebacondarwin commented
OK if you could rebase on main then we can see the diff.

2024-02-19 21:24 UTC, petebacondarwin approved these changes
Assuming the CI agrees.

2024-02-19 22:25 UTC, petebacondarwin requested changes
One last thing, regarding the changeset.
But otherwise looks smashing! Thanks.

2024-02-19 22:25 UTC, petebacondarwin commented on .changeset/sharp-snails-obey.md
> +"wrangler": patch
Strictly this is not a change to the Wrangler package. It is only changing some fixtures and templates, which are not deployed as part of Wrangler.
I think we could actually dispense with this changeset altogether.

2024-04-06 20:24 UTC, itsmatteomanf commented
I updated it so that it uses the `workspace:*` syntax in all cases...

2024-05-02 12:08 UTC, petebacondarwin approved these changes

2024-05-02 12:16 UTC, merged