Avoid blocking built-in node modules when using --no-bundle flag
cloudflare/workers-sdk pull request #4303
Opened 2023-10-30 09:45 UTC by richardscarrott

**What this PR solves / how to test:**

We want to import and use the [`AsyncLocalStorage` polyfil](https://developers.cloudflare.com/workers/runtime-apis/nodejs/asynclocalstorage/) in our Remix app, deployed to CF Pages.

However, to ensure Remix sourcemaps actually align with the executed code, we tell wrangler not to bundle our code and instead use [Advanced Mode](https://developers.cloudflare.com/pages/platform/functions/advanced-mode/) (_worker.js file).

```
npx wrangler pages deploy dist --project-name="${{ inputs.cloudflare_app }}" --branch="${{ inputs.cf_branch }}" --no-bundle
```

This fails with:

> _worker.js is not being bundled by Wrangler but it is importing from another file. This will throw an error if deployed. You should bundle the Worker in a pre-build step, remove the import if it is unused, or ask Wrangler to bundle it by setting`--bundle`

<img width="1318" alt="Screenshot 2023-10-29 at 18 09 41" src="https://github.com/cloudflare/workers-sdk/assets/539309/d393e061-1840-411f-bf92-0b8c8f165663">

<br />
<br />

After some [discussion in Discord](https://discord.com/channels/595317990191398933/789155108529111069/1168242491741450342), I believe this is a mistake because `node:async_hooks` _is_ available to import at runtime.

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

2023-10-30 10:17 UTC, Skye-31 commented on packages/wrangler/src/pages/functions/buildWorker.ts
> +			if (args.path.startsWith('node:')) {
Can you also check for `cloudflare:` prefixes 🙂

2023-10-30 14:18 UTC, petebacondarwin submitted a review, later dismissed
DONT MERGE - just testing approval

2023-10-30 16:57 UTC, Skye-31 reviewed
Thanks for the PR!

Could you add a test (see https://github.com/cloudflare/workers-sdk/blob/main/fixtures/pages-workerjs-app/tests/index.test.ts#L8), as well as a changeset (`pnpx changeset` in the root of the repo)

2023-12-11 16:23 UTC, penalosa commented
Apologies for the delay here—this is looking good! Before merging, could you add a unit test to https://github.com/cloudflare/workers-sdk/tree/main/packages/wrangler/src/__tests__/pages/deploy.test.ts ? I don't think this change will need a full fixture test

2024-01-29 15:57 UTC, lrapoport-cf commented
hi @richardscarrott :) could you please add a unit test (per @penalosa 's [comment](https://github.com/cloudflare/workers-sdk/pull/4303#issuecomment-1850417670))? else we'll close the PR and you can re-open when you're able to revisit and make the relevant changes. thanks!

2024-02-19 17:00 UTC, petebacondarwin requested changes
One small comment but otherwise LGTM!
Thanks

2024-02-19 17:00 UTC, petebacondarwin commented on packages/wrangler/src/pages/functions/buildWorker.ts
> +				args.path.startsWith("node:") ||
OK so I think we just need a bit of care here.
We should only consider imports beginning with `node:` as external if the `nodejs_compat` flag is actually turned on.

We can pass that through to this plugin by making it a function with a parameter, I believe.

2024-02-19 20:46 UTC, petebacondarwin approved these changes
I rebased, swapped out the fixture tests for unit tests, and added the check for the nodejs_compat flag.

@penalosa - PTAL

2024-02-20 11:25 UTC, penalosa approved these changes
One misplaced comment, but LGTM

2024-02-20 11:25 UTC, penalosa commented on packages/wrangler/src/__tests__/pages/deploy.test.ts
> +			// Add in a cloudflare import to the bundle
This comment seems out of place?

2024-02-20 21:08 UTC, merged