Improved tsconfig.json files in examples directory
cloudflare/workers-sdk pull request #4398
Opened 2023-11-08 11:10 UTC by mattpocock

**What this PR solves / how to test:**

Updates out-of-date configuration settings in some of the tsconfig.json in the examples. Also updates the initial tsconfig.init.json.

Based on information here:

https://www.totaltypescript.com/tsconfig-cheat-sheet

This is not complete - but a lot of what I've added can be added into other tsconfig.json files throughout the repo.

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [x] Not necessary because: just a change to the examples directory
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] Included
  - [x] Not necessary because: Unsure if this is a user-facing change

2023-11-08 12:24 UTC, RamIdeas approved these changes

2023-11-08 14:27 UTC, penalosa requested changes
Thanks for the PR! Unfortunately I don't think we can merge this yet, since the version of `esbuild` we use doesn't support TypeScript 5. We can definitely get it in after https://github.com/cloudflare/workers-sdk/issues/3962 though

2023-11-08 14:50 UTC, pmbanugo commented
> Thanks for the PR! Unfortunately I don't think we can merge this yet, since the version of `esbuild` we use doesn't support TypeScript 5. We can definitely get it in after #3962 though!

The current template (uses 5.0.4) and my workers already run using TypeScript 5. What's the issue with TS 5?

2024-07-04 17:01 UTC, penalosa approved these changes

2024-07-10 10:03 UTC, petebacondarwin commented
I added a changeset and ran the e2e tests locally. LGTM

2024-07-10 12:51 UTC, merged