tail: add a --force flag to bypass the DO prompt
cloudflare/workers-sdk pull request #4449
Opened 2023-11-15 17:32 UTC by elithrar

This PR adds a `--force` flag to `wrangler tail` to bypass the confirmation prompt for WebSocket/DO.

* It will still print the warning text
* Adds a changeset

cc @lrapoport-cf

2023-11-15 17:56 UTC, jspspike commented
This looks good to me, do you mind opening a PR in cloudflare-docs to update [this page](https://github.com/cloudflare/cloudflare-docs/blob/production/content/workers/wrangler/commands.md) with the new option?

2023-11-15 18:03 UTC, elithrar commented
@jspspike - already done / already mentioned in both PRs: https://github.com/cloudflare/cloudflare-docs/pull/11827

2023-11-15 19:30 UTC, jspspike approved these changes
Sorry didn't see the docs PR in the activity, could maybe use a test with the option. Otherwise looks good to me

2023-11-20 16:27 UTC, lrapoport-cf commented
hey @elithrar :) we discussed this as a team a bit more and agreed it would be good to have a test --  could you please add one? apologies we didn't catch it on the initial review!

2024-01-03 12:49 UTC, petebacondarwin requested changes
Please can you add a test for this functionality.
There is already one for the interactive behaviour: https://github.com/cloudflare/workers-sdk/blob/93833f0418443232bb29daf46559c8e1db754dde/packages/wrangler/src/__tests__/tail.test.ts#L59

2024-01-03 12:49 UTC, petebacondarwin commented on .changeset/rotten-keys-occur.md
> +"wrangler": patch
Minor I think - this is a small feature not a bug fix.

2024-01-10 15:21 UTC, closed without merging