[wrangler] fix: apply source mapping to deployment validation errors
cloudflare/workers-sdk pull request #4600
Opened 2023-12-13 11:36 UTC by mrbbot

Blocked by #4423.

Fixes #2741.

**What this PR solves / how to test:**

Previously if a Worker failed validation during `wrangler deploy`, the displayed error would reference locations in built JavaScript files. This made it more difficult to debug validation errors. This change ensures these errors are now source mapped, referencing locations in source files instead. To test this, try to deploy a TypeScript worker referencing a non-existent variable in the global scope. The validation error should include the location in the TypeScript file.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: change to error messaging

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

2023-12-19 12:05 UTC, RamIdeas approved these changes

2023-12-21 17:44 UTC, petebacondarwin requested changes
I know it is quite awkward but we might need to construct some actual source and compiled files, with source maps that can act as additional modules, etc so that we can cover the missing code-paths in tests.

2023-12-21 17:44 UTC, petebacondarwin commented on packages/wrangler/src/sourcemap.ts
> +export type RetrieveSourceMap = NonNullable<Options["retrieveSourceMap"]>;
NIT: I found this type a bit confusing to begin with. I would propose we call it `RetrieveSourceMapFunction` or `RetrieveSourceMapMethod`.

2023-12-21 17:44 UTC, petebacondarwin commented on packages/wrangler/src/sourcemap.ts
> +let retrieveSourceMapOverride: RetrieveSourceMap | undefined;
Why is this variable outside the `getSourceMappingPrepareStackTrace()` function? It doesn't seem to be used outside there?

2024-01-02 13:43 UTC, petebacondarwin commented on packages/wrangler/src/sourcemap.ts
> +let retrieveSourceMapOverride: RetrieveSourceMap | undefined;
Ah I see. That was not at all clear from the code - for me at least 😅.
I think a more detailed comment at this declaration would help future readers of the code.

2024-01-02 14:56 UTC, petebacondarwin approved these changes
Magic!

2024-01-02 14:56 UTC, petebacondarwin commented on packages/wrangler/src/__tests__/deploy.test.ts
> +					`interface Env {
You might like to consider the `dedent` utility here...

2024-01-02 15:33 UTC, merged