Make sure that the correct entrypoint file path is applied when bundling Pages applications
cloudflare/workers-sdk pull request #4676
Opened 2024-01-01 10:06 UTC by dario-piotrowicz

Fixes #4652 

TODO: add e2e tests for the changes here (if valuable)

2024-01-02 13:38 UTC, petebacondarwin requested changes
I think that `entry.file` should already be resolved by the time we hit this code.
In most cases it is. From looking up the call stack I think the problem is in `packages/wrangler/src/pages/dev.ts`: if the working `directory` is not defined then the `script-path` (aka `singleWorkerScriptPath`) is used without resolving it correctly.

2024-01-07 14:25 UTC, dario-piotrowicz commented
Thanks a bunch @petebacondarwin 🙂

I've applied the change in the `packages/wrangler/src/pages/dev.ts` hopefully that's what you had in mind please let me know how that looks 🙂

2024-01-09 17:39 UTC, petebacondarwin commented on fixtures/pages-dev-proxy-with-script/tests/index.test.ts
> +		debugger;
Remove?

2024-01-09 17:47 UTC, petebacondarwin approved these changes
I tested this locally by checking out the PR and running the following in the `pages-dev-proxy-with-script` fixture:

```
pnpm wrangler pages dev --proxy=9999 --script-path=custom/script/path/index.js
```

This fails with an error without the fix and works after the fix.

2024-01-11 22:09 UTC, merged