chore: change ignore list for node_modules to be less restrictive
cloudflare/workers-sdk pull request #4710
Opened 2024-01-05 23:30 UTC by nora-soderlund

Fixes #3615.

**What this PR solves / how to test:**
Currently, workers-sdk removes _any_ folder that is named node_modules. While intentions are good, this is inherently very restrictive and should not be done. This PR changes the ignore list to only remove the root folder node_modules.

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

2024-01-06 14:58 UTC, petebacondarwin requested changes
This would be a breaking change for some projects that point to directories that have nested `node_modules` directories that they don't want to be uploaded.

I think the correct approach is to allow the user to specify their own ignore list via some kind of configuration... perhaps follow the `.gitignore` or `.npmignore` files, or perhaps have a special `.pagesignore` file that does the job.

@nevikashah should chime in as this is a product change.

2024-01-06 15:33 UTC, nora-soderlund commented
I've added a `.pagesignore` alternative.

2024-01-08 14:36 UTC, GregBrimble commented
Hi, thank you for your PR! Unfortunately, I don't think this is something we're open to implementing right now, but we may revisit this in the future. Thank you for your suggestion.

2024-01-08 14:36 UTC, closed without merging

2024-01-08 16:49 UTC, nora-soderlund commented
Very unfortunate to see.

2024-01-09 16:32 UTC, nora-soderlund commented
Can we know of _why_ Cloudflare is not open to implementing this?

2024-01-10 17:01 UTC, nevikashah commented
Hey Nora! 

I’m a Product Manager on the Pages/Workers team. I wanted to first off take a moment to thank you for taking the time to write this PR. We are so grateful to have folks in our community like you who are passionate about bettering our products in this `workers-sdk` repo.  We are so lucky to have such an active contributor community - it is such an invaluable source of bug repos, ideas, and indeed, contributions! 

In the future, we're going to encourage contributors to first discuss the implementation with the team in the issue before spending time on it in a PR, so we can get alignment on which issues are ready to be worked on, and what the design for that change actually looks like. We're going to add notes to the `CONTRIBUTING.md` to that effect.

Though this PR wasn't accepted, we want to sincerely thank you for your contribution. We are sorry that we didn't have this process in place before you spent time on the PR and will absolutely do better next time to avoid this situation. 

In regards to this PR specifically: 

We're in the process of converging the Pages and Workers products which comes with its own set of challenges, and one of the really thorny ones is how to best handle configuration. Workers and Pages have different configuration options today (both because they have different features, and also because they were developed somewhat independently). 

They also have different mechanisms for managing that config (Pages is managed almost exclusively in the dashboard where config takes effect with the next deployment and has CLI args for local dev, whereas Workers supports file-based config — `wrangler.toml` — in-dash config which takes effect immediately and CLI args). We're looking to minimize any surface we can, and adding new config options, regardless of how that is set, would instead just add to the complexity of the problem. We're investigating a long-term and flexible configuration solution, such as  adding support for wrangler.toml in Pages. Here, we may allow users  to add things like include/exclude rules as part of the static asset config. 

So, in the meantime, we have decided to close this PR because rather than add this adhoc fix, we would really like to spend time and think about configuration holistically for Pages/Workers. 

Relatedly, the original issue here #3615 is closed as we don't consider that a bug in the current product — we're intentionally not uploading those folders. However, #3176 is a valid feature request, and one we're actively considering in the roadmap as discussed. It might not be a CLI arg, but the general idea of customizing which assets to upload is something that we're actively thinking about.

Again, I want to thank you again for taking the time to put your thoughts and ideas together in this PR. It is absolutely wonderful to see active developers such as yourself contributing to our `workers-sdk` repo.

2024-01-10 17:24 UTC, Cherry commented
The insight here is greatly appreciated @nevikashah.

I still don't entirely agree that this is being treated as a Feature Request and not a regression though. This used to work prior to https://github.com/cloudflare/workers-sdk/pull/2103, so while the feature request in https://github.com/cloudflare/workers-sdk/issues/3176 would indeed solve this, it's still technically a regression from prior functional behaviour, and has been reported and raised by both myself and others since 2022.

Nevertheless, thank you for the insight.

2024-01-10 19:01 UTC, nora-soderlund commented
Thank you for the explanation! I agree that for the long term it's more sustainable with a more shared and thought out approach.

However, for the short term, I would've suggested that an experimental flag is added. Something like --experimental-keep-node-modules or the alike, just making it explicit that it is a short term solution.

Either way - I understand the decision now that it's been explained, thank you. :)

2024-03-05 00:12 UTC, robertherber commented
@nevikashah Thanks for a great response explaining the background to this rejection. Still it's very sad to see this not being a higher priority since it's currently breaking all Expo Web projects, requiring manual workarounds specifically for deploying on Cloudflare Pages as reasoned about in #3615 with this [current workaround](https://github.com/expo/expo/issues/21568#issuecomment-1968405511)

2024-12-30 02:31 UTC, zhiyongsun commented
cloudflare lost 1 customer for this

2025-02-10 11:31 UTC, vishnuc commented
Hi ,its really regressive , we cannot add files which contain word node_modules ?? .. fix this issue its not feasible for react native expo project.

2025-02-10 12:38 UTC, nmassey commented
Hi @vishnuc - here's what I do to work around this. (This is similar to [the suggestion above](https://github.com/expo/expo/issues/21568#issuecomment-1968405511).)

1. In `package.json`:
```json
{
  "scripts": {
    "build:web": "expo export -p web && scripts/prep-for-cloudflare.sh",
  }
}
```

2. In `scripts/prep-for-cloudflare.sh`:
```sh
#!/bin/sh

# npx -y ts-node -T scripts/verify-paths.ts || exit 1

echo "Preparing for deployment on Cloudflare ..."
echo "Moving dist/assets/node_modules to dist/assets/nade_modules ..."
mv dist/assets/node_modules dist/assets/nade_modules
echo "Rewriting JS files "assets/node_modules" to "assets/nade_modules" in the following file(s):"
find dist/_expo/static/js/web/ -name "*.js" -type f -exec echo \{\} \;

# Mac sed requires a backup file extension for in-place editing
find dist/_expo/static/js/web/ -name "*.js" -type f -exec sed -ibak 's/assets\/node_modules/assets\/nade_modules/g' \{\} \;
find dist/_expo/static/js/web/ -name "*.jsbak" -type f -exec rm \{\} \;

echo "Done."
```

3. In Cloudflare Pages, I set my build command as `yarn build:web`

Good luck!

As an aside – you'll notice that in step 2 above I've commented out an `npx... || exit 1` command as a part of my shell script: in my actual script, this line is not commented out. I use this for some simple checks to ensure some expected files are found (e.g. `dist/.well-known/apple-app-site-association`, `dist/index.html`, `dist/expected-path/[value].html`, `functions/expected-path/[value].ts`) and to inspect the contents of some of these files for some simple sanity checks. I find this a nice failsafe: if some necessary contents are missing, I'd much rather have the build fail than deploy a broken site.