DRAFT: fix: pages-shared: Only apply early hints to html assets
cloudflare/workers-sdk pull request #4814
Opened 2024-01-22 23:29 UTC by jahands

Fixes # [insert GH or internal issue number(s)].

**What this PR solves / how to test:**

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

2024-01-26 18:19 UTC, jrf0110 approved these changes

2024-01-31 12:03 UTC, petebacondarwin requested changes

2024-01-31 12:03 UTC, petebacondarwin commented on packages/pages-shared/asset-server/handler.ts
> +	return contentType?.startsWith("text/html") || false;
This feels like a strong enough comment to warrant "requests changes" to this PR?

2024-04-22 21:10 UTC, jahands commented on .changeset/silly-llamas-flow.md
> +fix(pages-shared): Only apply early hints to html assets
Done

2024-04-22 21:20 UTC, jahands commented on packages/pages-shared/asset-server/handler.ts
> +	return contentType?.startsWith("text/html") || false;
Done, great catch @mrbbot! (miss ya!)

2024-04-22 21:34 UTC, jahands commented on packages/pages-shared/__tests__/asset-server/handler.test.ts
> +			`"</a.png>; rel="preload"; as=image, </b.png>; rel="preload"; as=image"`
Not sure why this had the escape characters before and not now, but it appears to match what early hints should look like: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

2024-04-22 21:37 UTC, jahands commented on packages/pages-shared/__tests__/asset-server/handler.test.ts
> +			`"</a.png>; rel="preload"; as=image, </b.png>; rel="preload"; as=image"`
This happened after rebase, so I'm presuming it's due to changes in miniflare / etc and may not reflect prod. Hopefully we can move these tests to the Vitest pool soon.

2024-04-22 21:37 UTC, jahands commented
@petebacondarwin This one should be good to go!

2024-04-24 18:35 UTC, jahands commented
rebased

2024-04-29 20:29 UTC, petebacondarwin commented on packages/pages-shared/environment-polyfills/miniflare.ts
> +	const { HTMLRewriter } = await import("@miniflare/html-rewriter");
Hmm. I don't know if we want to start depending upon the "old" Miniflare here.
Why does this need to be polyfilled?
Isn't it available inside workerd already?

2024-04-29 20:29 UTC, petebacondarwin commented on packages/pages-shared/package.json
> +		"@miniflare/html-rewriter": "^2.14.2",
These changes feel wrong to me. This means that this whole package starts depending upon the old deprecated Miniflare packages, right?

2024-04-29 20:37 UTC, petebacondarwin commented on packages/pages-shared/environment-polyfills/miniflare.ts
> +	const { HTMLRewriter } = await import("@miniflare/html-rewriter");
Well I can see that @mrbbot approved so perhaps this is fine.

2024-04-29 20:37 UTC, petebacondarwin commented on packages/pages-shared/package.json
> +		"@miniflare/html-rewriter": "^2.14.2",
OK, so happy to depend upon html-rewriter since @mrbbot approved. But why all these other `@miniflare` packages?

2024-04-30 14:49 UTC, petebacondarwin approved these changes

2024-04-30 14:50 UTC, merged