Deprecate `version` command
cloudflare/workers-sdk pull request #5069
Opened 2024-02-21 12:58 UTC by RamIdeas

**What this PR solves / how to test:**

This PR deprecated the `wrangler version` command. It does the same thing as `wrangler --version` which can be used instead. Deprecating because it could cause confusion with the upcoming `wrangler versions ...` commands.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: this command was never documented.

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

2024-02-23 20:11 UTC, penalosa requested changes

2024-03-05 16:32 UTC, RamIdeas commented on packages/kv-asset-handler/package.json
> +		"dev": "npm run build",
https://github.com/cloudflare/workers-sdk/pull/5069/commits/8a87bfa0f3675f3551acbde18afe07ba0998d1a3

2024-03-14 18:01 UTC, penalosa requested changes

2024-03-14 18:13 UTC, penalosa approved these changes

2024-03-15 13:18 UTC, merged