Remove second wrangler banner from namespace rename
cloudflare/workers-sdk pull request #5226
Opened 2024-03-11 20:43 UTC by DaniFoldi

## What this PR solves / how to test

After noticing #5225 and definitely not renaming a dispatch namespace a few times to see if the team notices it, I found that the banner was being printed twice in that command.

While the linked PR removes the yargs handler, it leaves the function in place, so I thought I'd fix it to aid a potential reintroduction in the future by ensuring the consistency between these functions.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [ ] Included
  - [x] Not necessary because: Banners are excluded from the snapshot the tests are checked against
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [x] Not necessary because: small banner fix

2024-03-12 13:04 UTC, rozenmd approved these changes

2024-03-12 14:05 UTC, petebacondarwin requested changes
The fact that there needs to be no change to a test for this to pass CI makes me worried about the test coverage here.
Could we add tests for this command? It should be quite straightforward, mocking out the fetch request expectation.

2024-03-12 17:17 UTC, nora-soderlund commented
is a community PR the best place to add _missing_ test coverage though? feels like something that should go to the employees backlog.

2024-03-12 21:39 UTC, petebacondarwin commented
> is a community PR the best place to add _missing_ test coverage though? feels like something that should go to the employees backlog.

Good call @nora-soderlund - I didn't notice that @DaniFoldi is not an employee. I totally don't expect him to backfill all our tests. But equally, this PR is fixing something that is not right in our codebase, so a test to prove it would be appreciated.

2024-04-02 18:08 UTC, DaniFoldi commented
Hey @petebacondarwin 👋 

I had a look at this, however it looks like it would require significant time to test that without having to change most tests.
If my investigation is correct, the header is disabled in tests to avoid tests failing every time when it changes (new version available, etc).
I think it should be possible to mock the header function and count its number of invocations. Failing on the second one could be possible by throwing, however detecting if a command is missing the header (r2 commands seem to have no header, for example) I'm not even sure how I'd approach.

Feel free to close this PR, or merge as-is, and the header stuff could be tracked in a separate issue.

2024-05-02 08:31 UTC, petebacondarwin approved these changes
I updated a test to prove this fix.

2024-05-02 09:05 UTC, merged