feat(wrangler-d1): Teach wrangler d1 insights about more timePeriods
cloudflare/workers-sdk pull request #5307
Opened 2024-03-20 02:48 UTC by achanda

## What this PR solves / how to test

This PR teaches `wrangler d1 insights` about more timePeriods. The input can now be of the form`\d+[dmh]`

Fixes #5048 

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [ ] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [ ] Not necessary because:

2024-03-20 09:38 UTC, rozenmd commented on .changeset/large-seals-kiss.md
> +"wrangler": major
```suggestion
"wrangler": patch
```

2024-03-20 09:40 UTC, rozenmd commented on .changeset/large-seals-kiss.md
> +Teach wrangler d1 insights about more timePeriods
```suggestion
fix: add more timePeriods to `wrangler d1 insights`

This PR updates `wrangler d1 insights` to accept arbitrary timePeriod values up to 31 days.
```

2024-03-20 09:42 UTC, rozenmd commented
Don't worry about tests/docs in this PR - we will start documenting this command soon, but have a pretty large refactor planned.

2024-03-20 17:20 UTC, achanda commented
Thanks @rozenmd all done now

2024-06-05 16:16 UTC, RamIdeas requested changes
LGTM I'm sure the existing behaviour of 1d, 7d or 31d is tested and continues to work with these changes but could you add some tests for other periods please?

2024-06-11 13:51 UTC, rozenmd commented
@RamIdeas I've added tests - the refactor hasn't happened yet, but this would still be useful in the meantime

2024-06-11 14:19 UTC, petebacondarwin approved these changes

2024-06-11 15:17 UTC, RamIdeas approved these changes

2024-06-11 15:18 UTC, merged