chore: apply prettier formatting to create-cloudflare tests
cloudflare/workers-sdk pull request #5393
Opened 2024-03-26 17:56 UTC by Cherry

## What this PR solves / how to test

Applies prettier formatting to vitest examples in c3, to match the formatting for the worker.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [ ] Included
  - [x] Not necessary because: No functional changes
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Included
  - [x] Not necessary because: No functional changes
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [x] Not necessary because: No functional changes

2024-04-06 18:00 UTC, jculvey approved these changes

2024-04-12 13:58 UTC, petebacondarwin approved these changes

2024-04-12 14:22 UTC, petebacondarwin requested changes
Actually I am a bit confused by this PR. Let me know if I missed the point.

It seems that compared to adding formatting to tests, it actually excludes formatting from the tests in C3 templates.
And also, since we are no longer formatting the tests in C3 templates, why are we updating the format of those?

2024-04-15 11:57 UTC, petebacondarwin commented
Right! My fault. It has been a bit of a long couple of weeks. I misread that you were adding these files back in to be formatted. All good. I'd like to see the e2e tests pass for this before merging. I'll push up a branch to our fork.

2024-04-17 09:40 UTC, petebacondarwin approved these changes

2024-04-17 09:40 UTC, merged