Support `wrangler pages secret put|delete|list|bulk`
cloudflare/workers-sdk pull request #5549
Opened 2024-04-07 16:13 UTC by penalosa

## What this PR solves / how to test

This PR supports adding secrets to a Pages project using the Wrangler CLI. Similarly to `wrangler secret`, this PR adds a `wrangler pages secret` set of commands. There are several differences to the Workers commands:
- `--project` is used to specify the project to target, compared to `--name` for Workers.
- The only environments that are supported are `--env=production|preview`
- `secret:bulk` is renamed to `secret bulk`
- The output is slightly friendlier

Fixes #5180

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] TODO (before merge)
  - [ ] Included
  - [ ] Not necessary because:
- Public documentation
  - [x] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [ ] Not necessary because:

2024-04-09 17:03 UTC, RamIdeas approved these changes

2024-04-09 17:31 UTC, admah requested changes
Left some suggestions for messaging updates.

2024-04-09 17:31 UTC, admah commented on packages/wrangler/src/pages/secret/index.ts
> +			"Create or update a secret variable for a Worker",
```suggestion
			"Create or update a secret variable for a Pages project",
```

2024-04-09 17:31 UTC, admah commented on packages/wrangler/src/pages/secret/index.ts
> +						describe: "The variable name to be accessible in the Worker",
```suggestion
						describe: "The variable name to be accessible in the Pages project",
```

2024-04-09 17:31 UTC, admah commented on packages/wrangler/src/pages/secret/index.ts
> +			"Delete a secret variable from a Worker",
```suggestion
			"Delete a secret variable from a Pages project",
```

2024-04-09 17:31 UTC, admah commented on packages/wrangler/src/pages/secret/index.ts
> +						describe: "The variable name to be accessible in the Worker",
```suggestion
						describe: "The variable name to be accessible in the Pages project",
```

2024-04-09 17:31 UTC, admah commented on packages/wrangler/src/pages/secret/index.ts
> +			"List all secrets for a Worker",
```suggestion
			"List all secrets for a Pages project",
```

2024-04-10 14:55 UTC, admah approved these changes
LGTM!

2024-04-10 16:11 UTC, merged