Check if NaN before incrementing highestMigrationNumber
cloudflare/workers-sdk pull request #7214
Opened 2024-11-10 14:49 UTC by lloydhumphreys

I ran into the following issue. If your first D1 migration is one you create and name manually with a single word (for example `init.sql`), then Wrangler will name all subsequent migrations `0NaN-...` because there are no `_` characters to split on so it'll take the word as a number.

I added a check for if the value is a number, and return 0 if not. So it'll start incrementing from 0 for new migrations created via wrangler.

---

- Tests
  - Not included. I wasn't sure they were necessary - if they are, I'll figure out how to do it.
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [x] I don't know
  - [ ] Required
  - [ ] Not required because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: I think people would presume it works like this already

2024-11-27 12:45 UTC, emily-shen commented
Hiya, thanks for putting up this PR! lgtm, just a few things to get this in :)
1. could you add a quick regression test? let me know if you run into any issues. Probably here - https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/__tests__/d1/migrate.test.ts 
2. there are some formatting errors, should go away if you run `pnpm fix`
3. can you add a changeset? should be a patch, and you can generate one by running `npx changeset`
thanks again for the contribution :)

2024-11-27 12:45 UTC, emily-shen requested changes
Hiya, thanks for putting up this PR! lgtm, just a few things to get this in :)
1. could you add a quick regression test? let me know if you run into any issues. Probably here - https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/__tests__/d1/migrate.test.ts 
2. there are some formatting errors, should go away if you run `pnpm fix`
3. can you add a changeset? should be a patch, and you can generate one by running `npx changeset`
thanks again for the contribution :)

2025-01-03 12:42 UTC, emily-shen approved these changes

2025-01-03 13:10 UTC, andyjessop approved these changes

2025-09-10 11:02 UTC, penalosa commented
I'm going to close this for now, since this has gotten pretty stale. After further discussion, this solution may have an issue with applying migrations on a fresh database, since manually named migrations (like `init.sql`) may not necessarily run in the correct order before numbered migrations.

2025-09-10 11:02 UTC, closed without merging