Print copyable wrangler.toml text when creating a hyperdrive config
cloudflare/workers-sdk pull request #7326
Opened 2024-11-22 20:48 UTC by OilyLime

Fixes #[SQC-348].

_Describe your change..._

This change gives wrangler users a quality of life improvement when creating a Hyperdrive config, giving them a copyable snippet to paste in their `wrangler.toml` file to bind their new Hyperdrive Config to their Worker.

---

- Tests
  - [ ] TODO (before merge)
  - [ ] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [ ] Not required because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [ ] Documentation not necessary because:

2024-11-25 15:34 UTC, penalosa requested changes
This should support both TOML & JSON

2024-11-25 15:34 UTC, penalosa commented on packages/wrangler/src/hyperdrive/create.ts
> +		TOML.stringify({
This should be using the new `formatConfigSnippet()` helper introduced in https://github.com/cloudflare/workers-sdk/pull/7230

2024-11-27 17:55 UTC, sejoker commented
> This should support both TOML & JSON

this is now addressed.

2024-11-27 17:56 UTC, penalosa approved these changes

2024-11-27 18:00 UTC, merged