SQC-352 SQC-353 Create cert upload command for client side mtls certificate/CA chain certificates
cloudflare/workers-sdk pull request #7466
Opened 2024-12-05 23:25 UTC by Ltadrian

Create cert upload command for client side mtls certificate/CA chain certificates

Fixes #[insert GH or internal issue link(s)].

- Allows the capability to upload custom CA certificates and client mTLS certificates. This is a lot similar to mtls-certificate command but our goal was to avoid confusion with workers support. This custom CA certificates upload is not a supported binding for workers. It will be available as a Hyperdrive binding very soon. 

Internal JIRA
[SQC-352](https://jira.cfdata.org/browse/SQC-352)
[SQC-353](https://jira.cfdata.org/browse/SQC-353)

---

- Tests
  - [ ] TODO (before merge)
  - [X] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [X] Required
  - [ ] Not required because:
- Public documentation
  - [X] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [ ] Documentation not necessary because:

2024-12-09 14:53 UTC, lrapoport-cf commented
hi @Ltadrian :) we recently introduced a new `createCommand` utility to be used when new commands are being added. can you please review https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CONTRIBUTING.md and update this PR accordingly? thank you!

2024-12-10 19:05 UTC, Ltadrian commented
> hi @Ltadrian :) we recently introduced a new `createCommand` utility to be used when new commands are being added. can you please review https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/CONTRIBUTING.md and update this PR accordingly? thank you!

this has been updated now, thank you 😄

2025-01-02 14:08 UTC, emily-shen requested changes
would also be great to add some e2e tests :)

2025-01-02 14:08 UTC, emily-shen commented on packages/wrangler/src/cert/cert.ts
> +        );
```suggestion
        const response = await confirm(
                `Are you sure you want to delete certificate ${certificate.id}${certificate.name ? `(${certificate.name})` : ""}?`
        );
```

nit 
(and for other similar log statements too)

2025-01-02 17:12 UTC, Ltadrian commented on packages/wrangler/src/__tests__/cert.test.ts
> +	const accountId = "1a2b3c4d";
removed accountId for `mockAccountId()`

2025-01-02 17:13 UTC, Ltadrian commented on packages/wrangler/src/cert/cert.ts
> +		status: "stable",
updated to `open-beta`

2025-01-02 17:14 UTC, Ltadrian commented on packages/wrangler/src/cert/cert.ts
> +        const certificates = await listMTlsCertificatesCA(accountId, {});
This is handled as part of this test here https://github.com/Ltadrian/workers-sdk/blob/ltadrian/cert-upload-mtls/packages/wrangler/src/__tests__/cert.test.ts#L370

2025-01-02 17:15 UTC, Ltadrian commented on packages/wrangler/src/api/mtls-certificate.ts
> +export async function uploadCaCertificates(
removed `uploadCaCertificates` and combined logic into `uploadCaCertificateFromFs`

2025-01-02 17:16 UTC, Ltadrian commented on packages/wrangler/src/cert/cert.ts
> +            certificate = await getMTlsCertificateByName(accountId, name as string);
Looks like the underlying api calls handle those errors, https://github.com/Ltadrian/workers-sdk/blob/ltadrian/cert-upload-mtls/packages/wrangler/src/api/mtls-certificate.ts#L157

2025-01-02 17:42 UTC, Ltadrian commented
> would also be great to add some e2e tests :)

is that required?

2025-01-03 11:53 UTC, emily-shen commented
> > would also be great to add some e2e tests :)
> 
> is that required?

yes, all new commands/features should have some happy-path e2e's before release :)

2025-01-14 11:51 UTC, emily-shen commented on packages/wrangler/e2e/cert.test.ts
is it possible to generate a new cert and key each time? Just concerned about simultaneous CI runs interfering with each other.

2025-01-14 17:56 UTC, Ltadrian commented on packages/wrangler/e2e/cert.test.ts
this has been updated to generate certs

2025-01-15 16:22 UTC, mtlemilio approved these changes
Minor observations.

2025-01-15 16:22 UTC, mtlemilio commented on packages/wrangler/src/api/mtls-certificate.ts
> +			certificates: readFileSync(details.certificates),
Should this be wrapped in a try block?

2025-01-15 16:22 UTC, mtlemilio commented on packages/wrangler/src/cert/cert.ts
> +// wrangler cert upload mtls-certificate
Need to update comment here.
```suggestion
// wrangler cert upload ca
```

2025-01-15 16:22 UTC, mtlemilio commented on packages/wrangler/src/cert/cert.ts
> +                logger.log(
Should we use the `formatConfigSnippet` here? Can these be bound directly to Workers?

2025-01-16 02:09 UTC, Ltadrian commented on packages/wrangler/src/cert/cert.ts
> +                logger.log(
mTLS certs can bound to workers but not CA certs. That's mainly why we created this new command to differentiate from the existing `mtls-certificate` command that is supported for workers. These will be used when creating Hyperdrive configs and not in toml bindings. The goal is to not have to set the certs in the workers and let hyperdrive deal with handling custom certs

2025-01-16 02:15 UTC, Ltadrian commented on packages/wrangler/src/api/mtls-certificate.ts
> +			certificates: readFileSync(details.certificates),
maybe not needed here, fetchResult internally has a try catch block and throws a specific error when the api request fails `throwFetchError(resource, json);` Seems to handle errors pretty well

2025-01-17 10:30 UTC, emily-shen approved these changes

2025-01-17 10:31 UTC, emily-shen commented
Approved pending tests passing :))

2025-01-22 10:38 UTC, merged