Add Warning about browser rendering when running locally
cloudflare/workers-sdk pull request #7533
Opened 2024-12-12 18:15 UTC by danielgek

Fixes #[insert GH or internal issue link(s)].

_Describe your change..._

---

- Tests
  - [ ] TODO (before merge)
  - [ ] Tests included
  - [x] Tests not necessary because: this just adds a warning
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: this just adds a warning
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: this just adds a warning

2024-12-17 10:27 UTC, CarmenPopoviciu commented on packages/wrangler/src/dev/miniflare.ts
> +		logger.warn("Browser render is not supported locally use `--remote`");
why is this added in `miniflare.ts`? This type of warnings and stdout logging in general is usually managed at command handler level. Which command(s) are targeted by this warning?

2024-12-17 10:30 UTC, CarmenPopoviciu commented
> Tests not necessary because: this just adds a warning

We usually test for this kind of stdout. See [here](https://github.com/cloudflare/workers-sdk/blob/2780849eb56b5e86210eb801ed91892d22ab9310/packages/wrangler/src/__tests__/dev.test.ts#L1736-L1743) for example. So we would def like to cover this warning as well by a unit test 🙏

2025-01-02 16:34 UTC, danielgek commented on packages/wrangler/src/dev/miniflare.ts
> +		logger.warn("Browser render is not supported locally use `--remote`");
I have done this here because I'm not sure how to do it in another way, I don't think we could do it on the command handler level because there I'm not sure we have access to the available bindings defined on the `wrangler.toml`

This will happen when a browser is defined on `wrangler.toml` and we run wrandler dev(local mode)

2025-01-02 17:02 UTC, emily-shen commented on packages/wrangler/src/dev/miniflare.ts
> +		logger.warn("Browser render is not supported locally use `--remote`");
I think `ConfigController.ts` might be a better spot for this - it's where we have similar warnings for remote/local mode so there should be some examples to work off there :)

2025-01-03 11:12 UTC, danielgek commented on packages/wrangler/src/dev/miniflare.ts
> +		logger.warn("Browser render is not supported locally use `--remote`");
@emily-shen can you take a look now ?

2025-01-03 11:25 UTC, emily-shen requested changes

2025-01-03 11:25 UTC, emily-shen commented on packages/wrangler/src/api/startDevWorker/ConfigController.ts
> +	if (resolved.bindings?.browser) {
i think you need to check if `resolved.dev.remote !== true` as well, otherwise this will always throw?

2025-01-03 11:29 UTC, danielgek commented on packages/wrangler/src/api/startDevWorker/ConfigController.ts
> +	if (resolved.bindings?.browser) {
you are totally right, pushed an update

2025-01-03 14:55 UTC, emily-shen commented
Agh so I had a look at why tests were failing. Turns out `resolved.bindings` is a record with binding name as the key, so the error wasn't actually throwing.
Anyway this should be the right check and passes locally for me
		`if(extractBindingsOfType("browser", resolved.bindings).length &&
		!resolved.dev.remote)`

2025-01-03 15:46 UTC, danielgek commented on packages/wrangler/src/api/startDevWorker/ConfigController.ts
> +			"Browser render is not supported locally. Please use `wrangler dev --remote` instead."
```suggestion
			"Browser Rendering is not supported locally. Please use `wrangler dev --remote` instead."
```

2025-01-03 15:48 UTC, danielgek commented
> Agh so I had a look at why tests were failing. Turns out `resolved.bindings` is a record with binding name as the key, so the error wasn't actually throwing. Anyway this should be the right check and passes locally for me `if(extractBindingsOfType("browser", resolved.bindings).length && !resolved.dev.remote)`

Nice, also i left some suggestions on working, would be nice if they can go in as well

And Thanks for all the help!

2025-01-03 19:26 UTC, merged