fix and update experimental Next.js template to work on `@opennextjs/cloudflare@0.3.x`
cloudflare/workers-sdk pull request #7638
Opened 2024-12-27 09:58 UTC by dario-piotrowicz

Changes made in `@opennextjs/cloudflare@0.3.0` haven't been updated in the C3 experimental template causing C3 to currently create broken open-next applications, this PR is addressing that plus some other small minor related  updates.

---

- Tests
  - [ ] TODO (before merge)
  - [ ] Tests included
  - [x] Tests not necessary because: the tests are already present
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Public documentation
  - [x] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [ ] Documentation not necessary because:

2024-12-27 10:00 UTC, dario-piotrowicz commented on packages/create-cloudflare/templates-experimental/next/templates/.gitignore
> -/.wrangler
We always add `.wrangler` to `.gitignore` files anyways: https://github.com/cloudflare/workers-sdk/blob/998902238552c860cf9dd9f629e8f351352ae3c4/packages/create-cloudflare/src/templates.ts#L802
so there's no reason to do that here as well

2024-12-27 10:01 UTC, dario-piotrowicz commented on packages/create-cloudflare/templates-experimental/next/templates/.gitignore
> -/.save.next
we don't have a `.save.next` dir anymore

2024-12-27 10:01 UTC, dario-piotrowicz commented on packages/create-cloudflare/templates-experimental/next/templates/.gitignore
> +# OpenNext
@vicb is there any new open-next file/directory that we should include here?

2024-12-27 11:03 UTC, vicb requested changes
Thanks

Could you please also add a .dev.vars, using https://github.com/flarelabs-net/workers-next/blob/main/.dev.vars.example as a template

2024-12-27 11:03 UTC, vicb commented on packages/create-cloudflare/templates-experimental/next/templates/wrangler.toml
> +main = ".open-next/index.mjs"
It should be worker.js

2024-12-27 11:10 UTC, dario-piotrowicz commented on packages/create-cloudflare/templates-experimental/next/templates/.gitignore
> +# OpenNext
yes I think it's ok too, I just wanted to double check, thanks 🙂

2024-12-27 13:03 UTC, vicb approved these changes
Thanks.

Maybe create an issue on https://github.com/opennextjs/docs to update the docs when this PR is released to c3

2024-12-27 14:09 UTC, dario-piotrowicz commented
> Thanks.
> 
> Maybe create an issue on https://github.com/opennextjs/docs to update the docs when this PR is released to c3

This is the Next.js guide that uses the open-next adapter: https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/

I don't think there's anything in the changes I'm making that needs updating there (otherwise I'd do it right away)

2024-12-27 15:34 UTC, edmundhung approved these changes

2024-12-27 18:35 UTC, vicb commented
> > Thanks.
> > Maybe create an issue on https://github.com/opennextjs/docs to update the docs when this PR is released to c3
> 
> This is the Next.js guide that uses the open-next adapter: https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/
> 
> I don't think there's anything in the changes I'm making that needs updating there (otherwise I'd do open a PR right away and merge it after the C3 release)

We need to update [that](https://github.com/opennextjs/docs/blob/main/pages/cloudflare/get-started.mdx#:~:text=npm%20create%20cloudflare%40latest%20%2D%2D%20%2D%2Dtemplate%20https%3A//github.com/flarelabs%2Dnet/workers%2Dnext) which is repeated multiple times to use the c3 experimental template

2024-12-27 23:28 UTC, dario-piotrowicz commented
> > > Thanks.
> > > Maybe create an issue on https://github.com/opennextjs/docs to update the docs when this PR is released to c3
> > 
> > 
> > This is the Next.js guide that uses the open-next adapter: https://developers.cloudflare.com/workers/frameworks/framework-guides/nextjs/
> > I don't think there's anything in the changes I'm making that needs updating there (otherwise I'd do open a PR right away and merge it after the C3 release)
> 
> We need to update [that](https://github.com/opennextjs/docs/blob/main/pages/cloudflare/get-started.mdx#:~:text=npm%20create%20cloudflare%40latest%20%2D%2D%20%2D%2Dtemplate%20https%3A//github.com/flarelabs%2Dnet/workers%2Dnext) which is repeated multiple times to use the c3 experimental template

ah ok, sorry I thought we were talking about the Cloudflare docs 👍

2024-12-27 23:36 UTC, dario-piotrowicz commented
@vicb https://github.com/opennextjs/docs/pull/44 👍

2024-12-30 10:09 UTC, dario-piotrowicz commented
Merging this PR as the only failing tests are e2es (both experimental and not) running nuxt using yarn under ubuntu and:
 - this PR is completely unrelated to nuxt
 - I can see the same failures in other existing PRs

2024-12-30 10:10 UTC, merged